### ISSUE TITLE
ayuda para enlazar intenciones

### ISSUE THREAD

**Issue by MrFiregore** [javichur/Alexa-Skill-Lavaplatos#1]
Buenas tardes,

Estoy desarrollando mi propia skill y me he bajado tu proyecto para aprender, pero soy incapaz de vincular los modelos (es-ES.json) para que cuando le diga "cancelar" se valla al manejador de cancelar, ¿podrías ayudarme?

**Comment by javichur** [comment]
Claro, te echo una mano. 
Entiendo que ya has entrado a la consola web de desarrolladores Alexa y has creado tu skill. A la hora de editar el modelo de voz desde dicha consola, ¿has pegado el contenido del fichero /modelo/es-ES.json dentro del editor json que hay en la consola web de desarrolladores Alexa?

**Comment by MrFiregore** [comment]
Oh muchísimas gracias, lo descubrí a las horas de publicar esta incidencia jajaja
Estoy desarrollando (casi terminada) una skill que te diga los casos de coronavirus, cuando la tenga publicada te la digo.
